### PR TITLE
GLX: Work around 'X_GLXCreateContextAtrribsARB' typo fix API break

### LINKED ISSUE #149: libglvnd fails to build with xorgproto
##### Description:

`libglvnd` fails to build with `xorgproto 2018.1-1` (replaced `glproto-1.4.17-1` )
https://www.archlinux.org/packages/extra/any/xorgproto/

```bash
libglx.c:282:29: error: use of undeclared identifier 'X_GLXCreateContextAtrribsARB'; did you mean 'glXCreateContextAttribsARB'?
                            X_GLXCreateContextAtrribsARB, True);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            glXCreateContextAttribsARB
libglx.c:265:19: note: 'glXCreateContextAttribsARB' declared here
static GLXContext glXCreateContextAttribsARB(Display *dpy, GLXFBConfig config,
                  ^
libglx.c:291:54: error: use of undeclared identifier 'X_GLXCreateContextAtrribsARB'; did you mean 'glXCreateContextAttribsARB'?
        vendor = CommonDispatchFBConfig(dpy, config, X_GLXCreateContextAtrribsARB);
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     glXCreateContextAttribsARB
libglx.c:265:19: note: 'glXCreateContextAttribsARB' declared here
static GLXContext glXCreateContextAttribsARB(Display *dpy, GLXFBConfig config,
                  ^
2 errors generated.
```
##### Additional info:

distro: Arch Linux
libglvnd: `r565.212861e`
side note: 
build finished successfully `libglvnd-git-r565.212861e + glproto-1.4.17-1`

### PR DESCRIPTION
**Pull request by aaronp24**
Older versions of glxproto.h contained a typo where "Attribs" was misspelled.
The typo was fixed in the xorgproto version of glxproto.h, breaking the API.

Fixes #149.

### CODE REVIEW

**Comment by aaronp24** [comment]
Kyle, do you want to work around this in libglvnd or push back on xorgproto to provide API compatibility? I was going to say that we could bump our glproto dependency and just fix the typo, but it looks like the old glproto package and the new xorgproto package both report version 1.4.17.

**Comment by kbrenneman** [comment]
I was figuring on adding a workaround to libglvnd, especially since it's a pretty simple one.

**Comment by nwnk** [comment]
I don't mind fixing glproto. The mesa code has always used the xcb enums and I didn't think there would be any other users.

**Comment by kbrenneman** [comment]
The upstream xorgproto headers now have the old misspelled constants in addition to the corrected ones, so libglvnd can build against them again.

@aaronp24 and @nwnk -- Do you think that's sufficient, or should we still make libglvnd be able to compile without the misspelled constants?

**Comment by aaronp24** [comment]
I don't have a strong preference either way.

**Comment by nwnk** [comment]
Slight preference to merge this. Occasionally one wants to grep all the code in the world, and when you do it's nice to have things spelled the way you expect.

**Comment by kbrenneman** [comment]
That's a good point.
