### ISSUE TITLE
libglvnd fails to build with xorgproto

### ISSUE THREAD

**Issue by fafryd1125** [NVIDIA/libglvnd#149]
##### Description:

`libglvnd` fails to build with `xorgproto 2018.1-1` (replaced `glproto-1.4.17-1` )
https://www.archlinux.org/packages/extra/any/xorgproto/

```bash
libglx.c:282:29: error: use of undeclared identifier 'X_GLXCreateContextAtrribsARB'; did you mean 'glXCreateContextAttribsARB'?
                            X_GLXCreateContextAtrribsARB, True);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            glXCreateContextAttribsARB
libglx.c:265:19: note: 'glXCreateContextAttribsARB' declared here
static GLXContext glXCreateContextAttribsARB(Display *dpy, GLXFBConfig config,
                  ^
libglx.c:291:54: error: use of undeclared identifier 'X_GLXCreateContextAtrribsARB'; did you mean 'glXCreateContextAttribsARB'?
        vendor = CommonDispatchFBConfig(dpy, config, X_GLXCreateContextAtrribsARB);
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     glXCreateContextAttribsARB
libglx.c:265:19: note: 'glXCreateContextAttribsARB' declared here
static GLXContext glXCreateContextAttribsARB(Display *dpy, GLXFBConfig config,
                  ^
2 errors generated.
```
##### Additional info:

distro: Arch Linux
libglvnd: `r565.212861e`
side note: 
build finished successfully `libglvnd-git-r565.212861e + glproto-1.4.17-1`

**Comment by aaronp24** [comment]
This is an API break in xorgproto vs. glproto. They fixed a typo in this define without providing a compatibility define.

I created https://github.com/NVIDIA/libglvnd/pull/150 to work around it in libglvnd.

**Comment by fafryd1125** [comment]
https://cgit.freedesktop.org/xorg/proto/xorgproto/commit/?id=c1c8cf73601e0e1fee843d338b3f0f5cc0bf1c17
